[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = [
  'solidity-utils/=lib/solidity-utils/src/',
  'hyperlane-monorepo/=lib/hyperlane-monorepo/solidity/contracts/',
  '@openzeppelin/=lib/openzeppelin-contracts/'
]
evm_version = 'shanghai'

fs_permissions = [{ access = "read-write", path = "./"}]

solc = "0.8.22"

[profile.default.zksync]
fallback_oz = true
mode = "3"
zksolc="1.4.1"

[rpc_endpoints]
ethereum="${RPC_MAINNET}"
ethereum-testnet="${RPC_ETHEREUM_SEPOLIA}"
polygon="${RPC_POLYGON}"
polygon-testnet="${RPC_POLYGON_MUMBAI}"
arbitrum="${RPC_ARBITRUM}"
arbitrum-testnet="${RPC_ARBITRUM_TESTNET}"
metis="${RPC_METIS}"
metis-testnet="${RPC_METIS_TESTNET}"
avalanche="${RPC_AVALANCHE}"
avalanche-testnet="${RPC_AVALANCHE_FUJI}"
optimism="${RPC_OPTIMISM}"
optimism-testnet="${RPC_OPTIMISM_TESTNET}"
fantom="${RPC_FANTOM}"
fantom-testnet="${RPC_FANTOM_TESTNET}"
binance="${RPC_BINANCE}"
binance-testnet="${RPC_BINANCE_TESTNET}"
base="${RPC_BASE}"
base-testnet="${RPC_BASE_TESTNET}"
gnosis="${RPC_GNOSIS}"
gnosis-testnet="${RPC_GNOSIS_TESTNET}"
zkevm="${RPC_ZKEVM}"
zkevm-testnet="${RPC_ZKEVM_TESTNET}"
scroll="${RPC_SCROLL}"
scroll-testnet="${RPC_SCROLL_TESTNET}"
celo="${RPC_CELO}"
celo-testnet="${RPC_CELO_ALFAJORES}"
zksync="${RPC_ZK_SYNC}"
zksync-testnet="${RPC_ZK_SYNC_TESTNET}"

[etherscan]
ethereum={key="${ETHERSCAN_API_KEY_MAINNET}", chain=1 }
ethereum-testnet={key="${ETHERSCAN_API_KEY_MAINNET}",chain=11155111}
optimism={key="${ETHERSCAN_API_KEY_OPTIMISM}",chain=10}
optimism-testnet={key="${ETHERSCAN_API_KEY_OPTIMISM}",chain=10}
avalanche={key="${ETHERSCAN_API_KEY_AVALANCHE}",chain=43114}
avalanche-testnet={key="${ETHERSCAN_API_KEY_AVALANCHE}",chain=43113}
polygon={key="${ETHERSCAN_API_KEY_POLYGON}",chain=137}
polygon-testnet={key="${ETHERSCAN_API_KEY_POLYGON}",chain=80001}
arbitrum={key="${ETHERSCAN_API_KEY_ARBITRUM}",chain=42161}
arbitrum-testnet={key="${ETHERSCAN_API_KEY_ARBITRUM}",chain=42161}
metis={ key="any", chain=1088, url='https://andromeda-explorer.metis.io/' }
metis-testnet={ key="any", chain=599, url='https://goerli.explorer.metisdevops.link/' }
fantom={key="${ETHERSCAN_API_KEY_FANTOM}",chain=250}
fantom-testnet={key="${ETHERSCAN_API_KEY_FANTOM}",chain=250}
binance={key="${ETHERSCAN_API_KEY_BINANCE}",chain=56}
binance-testnet={key="${ETHERSCAN_API_KEY_BINANCE}",chain=97}
base={key="${ETHERSCAN_API_KEY_BASE}",chain=8453, url='https://developer-access-mainnet.base.org'}
base-testnet={key="${ETHERSCAN_API_KEY_BASE}",chain=8453, url='https://developer-access-mainnet.base.org'}
gnosis={key="${ETHERSCAN_API_KEY_GNOSIS}",chain=100}
gnosis-testnet={key="${ETHERSCAN_API_KEY_GNOSIS}",chain=10200, url='https://gnosis-chiado.blockscout.com/'}
zkevm={key="${ETHERSCAN_API_KEY_ZKEVM}",chain=1101}
zkevm-testnet={key="${ETHERSCAN_API_KEY_ZKEVM}",chain=1442}
scroll={key="${ETHERSCAN_API_KEY_SCROLL}", chain=534352, utl='https://api.scrollscan.com/api/'}
scroll-testnet={key="${ETHERSCAN_API_KEY_SCROLL}", chain=534351, url='https://api-sepolia.scrollscan.com/api/'}
celo={key="${ETHERSCAN_API_KEY_CELO}", chain=42220, utl='https://api.celoscan.io/api'}
celo-testnet={key="${ETHERSCAN_API_KEY_CELO}", chain=44787, url='https://api-alfajores.celoscan.io/api'}
zksync={key="${ETHERSCAN_API_KEY_ZK_SYNC}", chain=324}
zksync-testnet={key="${ETHERSCAN_API_KEY_ZK_SYNC}", chain=300, url='https://api-sepolia-era.zksync.network/api'}

# See more config options https://github.com/gakonst/foundry/tree/master/config
[fuzz]
no_zksync_reserved_addresses = true
[invariant]
no_zksync_reserved_addresses = true
