[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = [
  'solidity-utils/=lib/solidity-utils/src/',
  'hyperlane-monorepo/=lib/hyperlane-monorepo/solidity/contracts/',
  '@openzeppelin/=lib/openzeppelin-contracts/'
]

fs_permissions = [{ access = "read-write", path = "./"}]

solc = "0.8.19"

[rpc_endpoints]
ethereum="${RPC_MAINNET}"
ethereum-testnet="${RPC_MAINNET_TESTNET}"
polygon="${RPC_POLYGON}"
polygon-testnet="${RPC_POLYGON_TESTNET}"
arbitrum="${RPC_ARBITRUM}"
arbitrum-testnet="${RPC_ARBITRUM_TESTNET}"
metis="${RPC_METIS}"
metis-testnet="${RPC_METIS_TESTNET}"
avalanche="${RPC_AVALANCHE}"
avalanche-testnet="${RPC_AVALANCHE_TESTNET}"
optimism="${RPC_OPTIMISM}"
optimism-testnet="${RPC_OPTIMISM_TESTNET}"
fantom="${RPC_FANTOM}"
fantom-testnet="${RPC_FANTOM_TESTNET}"
binance="${RPC_BINANCE}"
binance-testnet="${RPC_BINANCE_TESTNET}"
base="${RPC_BASE}"
base-testnet="${RPC_BASE_TESTNET}"
zkevm="${RPC_ZKEVM}"
zkevm-testnet="${RPC_ZKEVM_TESTNET}"

[etherscan]
ethereum={key="${ETHERSCAN_API_KEY_MAINNET}", chain=1 }
ethereum-testnet={key="${ETHERSCAN_API_KEY_MAINNET}",chain=1}
optimism={key="${ETHERSCAN_API_KEY_OPTIMISM}",chain=10}
optimism-testnet={key="${ETHERSCAN_API_KEY_OPTIMISM}",chain=10}
avalanche={key="${ETHERSCAN_API_KEY_AVALANCHE}",chain=43114}
avalanche-testnet={key="${ETHERSCAN_API_KEY_AVALANCHE}",chain=43114}
polygon={key="${ETHERSCAN_API_KEY_POLYGON}",chain=137}
polygon-testnet={key="${ETHERSCAN_API_KEY_POLYGON}",chain=137}
arbitrum={key="${ETHERSCAN_API_KEY_ARBITRUM}",chain=42161}
arbitrum-testnet={key="${ETHERSCAN_API_KEY_ARBITRUM}",chain=42161}
metis={ key="any", chain=1088, url='https://andromeda-explorer.metis.io/' }
metis-testnet={ key="any", chain=599, url='https://goerli.explorer.metisdevops.link/' }
fantom={key="${ETHERSCAN_API_KEY_FANTOM}",chain=250}
fantom-testnet={key="${ETHERSCAN_API_KEY_FANTOM}",chain=250}
binance={key="${ETHERSCAN_API_KEY_BINANCE}",chain=56}
binance-testnet={key="${ETHERSCAN_API_KEY_BINANCE}",chain=56}
base={key="${ETHERSCAN_API_KEY_BASE}",chain=8453, url='https://developer-access-mainnet.base.org'}
base-testnet={key="${ETHERSCAN_API_KEY_BASE}",chain=8453, url='https://developer-access-mainnet.base.org'}

# See more config options https://github.com/gakonst/foundry/tree/master/config
